### ISSUE TITLE
forked repo hidden from searches

### ISSUE THREAD

**Issue by gilesknap** [yannrouillard/gphotos-sync#11]
Hi Yan,

I'd like, with your permission to divorce my fork of gphotos-sync from your original. This is because it is very difficult to find my project fork by searching github. Now that you have deprecated and no longer have keywords relating to google photos it is almost impossible to find my project.

I believe that this is possible through github support but would like to make sure you are OK with it.

Thanks

**Comment by yannrouillard** [comment]
Hi gilesknap,

Of course you can do it !

Yann

**Comment by yannrouillard** [comment]
(Hope you already done it without waiting for my permission !)

**Comment by gilesknap** [comment]
I did wait. But it is sorted now. Thanks.
