### ISSUE TITLE
Please give option not to sync photos sent from contacts

### ISSUE THREAD

**Issue by ghost** [yannrouillard/gphotos-sync#4]
Please give option not to sync photos sent from contacts

I want to sync only what I've filmed and not necessarily all of what was sent to me.

**Comment by yannrouillard** [comment]
Hi @ghost,

I am not sure I know how to detect photos sent by contacts in Google Photos (at least with Google Drive API or Picasa API, maybe better with official Google Photos API that Google released meanwhile).

Anyway, I don't maintain this project anymore so I will close this bug.
If you are still interested in such a tool, I recommend you have a look at https://github.com/gilesknap/gphotos-sync which is a fork of this project with considerable changes to improve it.

**Comment by gilesknap** [comment]
Hi @ghost - the new API which I'm using in the fork (https://github.com/gilesknap/gphotos-sync ) does give information about shared folders and who created the photo.

If you are interested I could add a feature to filter on the creator.
