### ISSUE TITLE
Add clarification to README on use case relative to Google Drive

### ISSUE THREAD

**Issue by felciano** [yannrouillard/gphotos-sync#9]
This looks like a very useful utility, but possibly duplicates some of the capabilities that are built into Google Photos and Google Drive, whereby you can expose your photos in a "Google Photos" folder in Google Drive, and then sync the latter to your local hard drive with Google Backup & Sync.

Would it be possible to add a few lines of explanatory text to the README that either confirms this (i.e. `gphotos-sync` is another way of accomplishing the same thing), or explaining some of the unique capabilities for this tool (e.g. works around limitations of the Google Backup & Sync features).

Thanks!

**Comment by yannrouillard** [comment]
Hi Felciano,

You are right about the missing explanation (you can find some explanation in this ticket: https://github.com/yannrouillard/gphotos-sync/issues/3#issuecomment-320648079).

Anyway, I don't maintain this project anymore, I will not update it anymore so I will close this bug.
You are better moving to https://github.com/gilesknap/gphotos-sync which is a fork of this project with considerable changes to improve it.
